# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15network_service.proto\x12\x0fnetwork_service\"^\n\x0f\x43hangeIPRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x16\n\x0einterface_name\x18\x02 \x01(\t\x12\x0f\n\x07netmask\x18\x03 \x01(\t\x12\x0f\n\x07gateway\x18\x04 \x01(\t\"4\n\x10\x43hangeIPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2a\n\x0eNetworkService\x12O\n\x08\x43hangeIP\x12 .network_service.ChangeIPRequest\x1a!.network_service.ChangeIPResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGEIPREQUEST']._serialized_start=42
  _globals['_CHANGEIPREQUEST']._serialized_end=136
  _globals['_CHANGEIPRESPONSE']._serialized_start=138
  _globals['_CHANGEIPRESPONSE']._serialized_end=190
  _globals['_NETWORKSERVICE']._serialized_start=192
  _globals['_NETWORKSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
